### ISSUE TITLE
Accès admin au repo Duralex pour l’équipe Duralex

### ISSUE THREAD

**Issue by Seb35** [Legilibre/salon#13]
@fgallaire: @promethe42 a transféré son repo "duralex" vers Legilibre – c’est le projet de projection d’amendements sur la loi en vigueur – mais il n’a plus le droit d’owner sur le repo. J’ai créé l’équipe Duralex mais il semble que je ne peux pas non plus attribuer le repo Duralex à l’équipe Duralex. Je pense qu’il n’y a que toi qui peut faire cette manip en tant qu’owner de Legilibre, tu peux t’en occuper ?

**Comment by fgallaire** [comment]
Fait.
