### ISSUE TITLE
Dons à Légilibre

### ISSUE THREAD

**Issue by Changaco** [Legilibre/salon#3]
Ce serait bien de pouvoir dire aux personnes à qui on parle de Légilibre : « vous pouvez soutenir ce travail en faisant un don ». La possibilité de créer une association a déjà été évoquée en privé, mais c'est lourd et on n'a pas besoin de ça pour recevoir des dons : on peut créer [une équipe sur Liberapay](https://liberapay.com/about/teams).

**Qui est favorable à la création d'une équipe Liberapay ? Au contraire y a-t-il quelqu'un qui s'y oppose ?**

Je précise que je suis le créateur de Liberapay, pour ceux ici qui ne me connaissent pas.

Si vous êtes favorable et souhaiteriez faire partie de l'équipe je vous invite à [créer votre compte Liberapay](https://liberapay.com/sign-up) puis à poster ici votre nom d'utilisateur (nécessaire pour pouvoir vous inviter à rejoindre l'équipe le moment venu).

**Comment by fgallaire** [comment]
Typiquement ce genre de débat est meilleur en interne.

**Comment by Changaco** [comment]
Si quelqu'un ne souhaite pas répondre en public il peut le faire en privé. Moi j'ai considéré qu'il n'y avait rien de sensible dans mon message donc je l'ai envoyé en public.

**Comment by benjaminvialle** [comment]
Plutôt favorable même si c'est peut-être un peu prématuré :)
(Je suis sur Liberapay, mon identifiant est facile à deviner)

**Comment by Changaco** [comment]
@benjaminvialle Peux-tu préciser ta pensée ? En quoi est-ce « peut-être un peu prématuré » ?

**Comment by Seb35** [comment]
Je suis pour créer un compte Liberapay, et je viens de m’y créer un compte personnel Seb35. Dans les dépenses immédiates faites au nom de Légilibre, il y aurait déjà un serveur commun où stocker un mirroir des bases + y faire tourner les scripts (enfin Florent et moi en avions parlé et je l’avais évoqué sur #1). Cette dépense est pas énorme, mais si elle était financée ça serait toujours ça de pris + ça montrerait que Légilibre a un soutien financier (au niveau de la communication).

**Comment by fgallaire** [comment]
Le problème de Liberapay c'est que c'est une plateforme confidentielle, et elle ne va pas "aider" Légilibre à se financer. Maintenant si ça vous plaît allons-y, au pire il n'y aura pas d'argent au bout et on ira ailleurs.

**Comment by JMLX42** [comment]
https://opencollective.com/

**Comment by fgallaire** [comment]
@promethe42 je ne connaissais pas, mais ça ressemble beaucoup à ce qu'il nous faudrait

**Comment by JMLX42** [comment]
Je connais le fondateur. On en a déjà discuté pour Cocorico.
Seul problème : il faut un organisme "hôte" qui a un compte et une existence légale dans le pays concerné. Et pas encore d'hôte en France...

On pourrait créer une association hôte "CivicTech" par exemple. Et tous les projets civic tech open source français pourrait donc se greffer dessus via OpenCollective.
En prenant une quotisation de 10%, on aurait de quoi payer la structure...

Qu'en penses-tu ?

**Comment by fgallaire** [comment]
@promethe42 j'ai vraiment l'impression qu'OpenCollective résout plus de problèmes que Liberapay, cependant je ne me vois pas me lancer dans la mise en place d'un organisme "hôte" ni prélever une cotisation.

En conséquence, @Changaco je pense que Liberapay est probablement la moins mauvaise des solutions si on veut récupérer quelques fonds.

**Comment by Changaco** [comment]
Je ne suis pas prêt à créer une équipe pour Légilibre. Premièrement car la discussion ci-dessus ne me donne pas envie de le faire. Deuxièmement car Légilibre n'est pas un projet avec une mission claire mais un groupe de projets sans cohérence globale, ce qui augmente la probabilité d'un conflit sur la répartition du revenu. D'ailleurs je ne saurais pas à combien fixer ma part si je créais l'équipe maintenant, et je ne saurais pas quoi mettre comme message de présentation sur la page de l'équipe.

Les équipes Liberapay sont conçues pour rémunérer du travail, pas pour faire du remboursement de frais (comme elles n'ont pas d'existence légale elles ne peuvent pas stocker des fonds pour de futures dépenses). L'implémentation des remboursements de frais et du *fiscal sponsorship* dans Liberapay est prévue, mais il va falloir patienter un peu.

**Comment by fgallaire** [comment]
Oui effectivement, l'objectif est de payer les frais de structure et non pas de rémunérer les développeurs (ce qui serait de toute manière impossible).

**Comment by fgallaire** [comment]
Liberapay comme toute solution centralisée ne peut résoudre convenablement le problème. Espérons qu'une des ICO actuelles portera le bon projet.
