### ISSUE TITLE
Nuit du Code citoyen, Paris, 4-5 mars

### ISSUE THREAD

**Issue by Seb35** [Legilibre/salon#9]
Si vous êtes dispo les samedi-dimanche 4-5 mars, il y a la [Nuit du Code citoyen](http://codecitoyen.github.io) à Paris et ailleurs.

@promethe42 et moi allons à la version parisienne pour avancer sur le projet évoqué sur https://github.com/Legilibre/salon/issues/6#issuecomment-277523738 (en gros codes + amendements = loi [possiblement] à venir et coupler ça à une plateforme de vote pour #MaVoix) et @valentinchaput fait partie de l’orga. Mais plus largement ça peut être un rendez-vous entre nous, légilibristes, pour faire avancer nos projets collectivement.

Voilà, l’idée est lancée, à vous !

**Comment by fgallaire** [comment]
Vous voulez y aller en tant que "participant" ou en tant que "porteur de projet" ?

**Comment by JMLX42** [comment]
> Vous voulez y aller en tant que "participant" ou en tant que "porteur de projet" ?

En tant que porteur de projet. On a déjà pas beaucoup de temps pour coder, on va pas y aller pour coder sur les projets des autres ^^

**Comment by fgallaire** [comment]
Je vais essayer de venir

**Comment by Seb35** [comment]
Petit résumé à la fin du premier jour
---------------

[Pad de travail](https://annuel.framapad.org/p/law-is-code-citoyen)

Jean-Marc et moi avons présenté en plénière Légilibre et #MaVoix ainsi que le projet Légilibre x #MaVoix de projection des amendements sur la loi actuelle.

Nous sommes 6 dans le groupe, @promethe42, @Pierrot-ongit, moi, Elyes, Sam, Benoît. Après un point de présentations personnelles et des projets, Jean-Marc a fait un graphe entre les différents projets et la base de données de legi.py est placée au cœur de Archéo Lex et de [Wikilex](http://www.wikilex.xyz) (les deux projets doivent maintenant l’intégrer dans les programmes). Seb a montré comment lancer legi.py et la structure basique de la base de données. Pierre a montré l’architecture de son site dédié à l’exploration des codes. Jean-Marc a montré comment utiliser le [parseur d’amendements](https://github.com/promethe42/the-law-factory-parser/tree/feature/parse_texte_ast), son architecture et proposé un jeu pour améliorer le parseur : une appli web avec le code du parseur dans une fenêtre et le résultat mis à jour en temps réel dans une autre.

Ensuite on a créé un petit amendement fictif [1] qui servira de test en étant appliqué sur le [code des instruments monétaires et des médailles](https://github.com/Seb35/CIMM-articles). Jean-Marc a orchestré l’après-midi et étudié [ParlAPI](http://parlapi.fr). Seb et Pierre ont créé un [https://github.com/promethe42/the-law-factory-parser/tree/feature/parse_texte_ast](diagramme du schéma de base de données legi.py). Benoît (graphiste) a étudié les différentes interfaces de visualisation des diffs. Elyes et Sam (développeurs) ont commencé à écrire un programme pour appliquer les "diffs abstraits" (l’AST issu du parseur d’amendements) sur un texte.

Plus de détails sur [le pad de travail](https://annuel.framapad.org/p/law-is-code-citoyen).

[1] À l'article 9 du code des instruments monétaires et des médailles, le mot "défendu" est remplacé par le mot "autorisé".

**Comment by Changaco** [comment]
Super tout ça. :-)

**Comment by Seb35** [comment]
Petit résumé du deuxième jour
------------------

On a tous continué à la suite de ce qu’on avait commencé. En fin de journée, Jean-Marc, Pierre, Benoît et moi avons présenté les résultats ; a priori la vidéo a été diffusée aux autres Nuits du code citoyen et enregistrée par Paul, notre hôte du [Square](https://www.openstreetmap.org/node/1301155796).

Les résultats sont donc :
* Pierre a essayé d’importer la base de legi.py (que j’avais générée et lui avait donnée) dans MySQL ; @Changaco, @Pierrot-ongit a fait une proposition de modification sur https://github.com/Pierrot-ongit/legi.py/commits/patch-1 ; par contre Pierre il faut que tu fasse la "pull request" pour proposer "officiellement" la modification à Changaco ; et si tu peux ajouter l’autre proposition de modification sur le titrefull_s ;
* @SamyMe et @eighilaza ont terminé avec succès [https://github.com/Legilibre/NuitCodeCitoyen](le prototype) pour appliquer les “diffs AST” en “diffs sur un texte donné” ; ce programme prend donc en entrée la sortie de Jean-Marc et un répertoire contenant les codes et lois au format https://github.com/Legilibre/CIMM-articles et rend en sortie [un diff comme celui-ci](https://github.com/Legilibre/CIMM-articles/commit/e476fbc1bd0254cdf1c85348bfd3e7e45c738ca9) (ici c’est moi qui l’ai fait, mais leur programme fait le même) (pour l’instant, c’est un prototype, je pense pas qu’il sélectionne le nom du code, mais le programme est conçu pour le faire à terme) ;
* Benoît a installé une VM Ubuntu sur son Mac, a installé Gitlab dedans, a commencé à apprendre React pour créer une interface de présentation des diffs+vote et a créé un début d’interface pour afficher un diff à l’aide d’un module React ;
* j’ai commencé à intégrer legi.py dans Archéo Lex, ça fonctionne un peu mais ça n’est pas fini ; j’ai aussi regardé un peu React pour apprendre un peu pour aider à l’interface ;
* Jean-Marc a aidé Elyes et Samy pour le programme AST2diff et Benoît dans l’apprentissage de la manipulation de VMs et de React.

En résumé, legi.py est en passe de devenir LE standard de base structurée de la base LEGI :) et la faisabilité du pipeline LEGI + amendement => diffs est prouvée, il ne reste _plus qu’à_ améliorer, optimiser, débugger, industrialiser, créer une interface et mettre en prod.

EDIT:
* Côté future organisation, j’ai créé le dépôt https://github.com/Legilibre/NuitCodeCitoyen sur Légilibre, il contient actuellement le prototype essentiellement pour le stocker, mais il faudra très probablement réorganiser le code pour notamment en faire un dépôt et un code indépendant.
* Je viens de renommer https://github.com/Seb35/CIMM-articles en https://github.com/Legilibre/CIMM-articles

**Comment by Seb35** [comment]
Le résumé qu’a fait Jean-Marc sur le forum de #MaVoix : https://forum.mavoix.info/t/hackathon-nuit-du-code-citoyen-le-4-mars/1141/8
